app_home:
    path: /
    controller: App\WebshopBundle\Presentation\Web\Controller\HomeController::index

app_login:
    path: /login
    controller: App\WebshopBundle\Presentation\Web\Controller\LoginController::index

app_oauth_connect:
    path: /auth/connect
    controller:  App\WebshopBundle\Presentation\Web\Controller\OauthLoginController::connect

app_connect_check:
    path: /auth/connect_check
    controller:  App\WebshopBundle\Presentation\Web\Controller\OauthLoginController::connectCheck

app_signup:
    path: /signup
    controller:  App\WebshopBundle\Presentation\Web\Controller\CustomerController::signUp

app_account:
    path: /account
    controller:  App\WebshopBundle\Presentation\Web\Controller\CustomerController::account

app_customer_space:
    path: /catalog
    controller: App\WebshopBundle\Presentation\Web\Controller\CustomerSpaceController::index

api_registration:
    path: /api/registration
    controller:  App\WebshopBundle\Presentation\Api\Rest\RegistrationController::registration

app_logout:
    path: /logout
    methods: GET

add_to_cart:
    path: cart/add
    controller: App\WebshopBundle\Presentation\Web\Controller\CartController::addToCart
    methods: POST

remove_from_cart:
    path: cart/removeItem/{itemId}
    controller: App\WebshopBundle\Presentation\Web\Controller\CartController::removeItemFromCart
    methods: GET

cart:
    path: /cart
    controller: App\WebshopBundle\Presentation\Web\Controller\CartController::index
    methods: GET

checkout:
    path: /checkout
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutController::index
    methods: GET

addCustomer:
    path: /checkout
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutController::addCustomer
    methods: POST

checkoutStep2:
    path: /checkout/step/2
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutController::createShippingMethod
    methods: GET

addShippingMethod:
    path: /checkout/step/2
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutController::addShippingMethod
    methods: POST

checkoutStep3:
    path: /checkout/step/3
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutController::createPaymentMethod
    methods: GET

addPaymentMethod:
    path: /checkout/step/3
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutController::addPaymentMethod
    methods: POST

checkoutdummyinit:
    path: /dummy/checkoutinit
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutDummyController::init
    methods: POST

shipping_dummy:
    path: /dummy/shipping
    controller: App\WebshopBundle\Presentation\Web\Controller\ShippingDummyController::init
    methods: POST

payment_dummy:
    path: /dummy/payment
    controller: App\WebshopBundle\Presentation\Web\Controller\PaymentDummyController::init
    methods: POST

checkoutdummyinit2:
    path: /dummy/customer
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutDummyController::init2
    methods: POST

shipping:
    path: /shipping
    controller: App\WebshopBundle\Presentation\Web\Controller\ShippingController::index
    methods: GET

get_checkout_dummy_init:
    path: /dummy/customer
    controller: App\WebshopBundle\Presentation\Web\Controller\CheckoutDummyController::initGetCheckout
    methods: POST
    
thankyou:
    path: /thankyou
    controller: App\WebshopBundle\Presentation\Web\Controller\ThankYouController::index
    methods: GET
