services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\WebshopBundle\:
        resource: '../../../../WebshopBundle'
        exclude:
            - './WebshopBundle/DependencyInjection/'
            - './WebshopBundle/Entity/'
            - './WebshopBundle/Kernel.php'

    App\WebshopBundle\Presentation\Web\Controller\: # assuming you have namespace like that
        resource: '../../../Presentation/Web/Controller'
        tags: [ 'controller.service_arguments' ]

#Message bus definition
    App\WebshopBundle\Application\Registration\RegistrationCommandHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\Registration\RegistrationCommand

    App\WebshopBundle\Application\SubscribeToNewsletter\SubscribeToNewsletterHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\SubscribeToNewsletter\SubscribeToNewsletterCommand

    App\WebshopBundle\Application\Account\QueryCustomerAccountHandler:
        tags:
            - name: messenger.message_handler
              bus: command.bus
              handles: App\WebshopBundle\Application\Account\QueryCustomerAccountCommand

    App\WebshopBundle\Application\Catalog\GetProductCatalog\GetProductCatalogHandler:
        tags:
            -   name: messenger.message_handler
                handles: App\WebshopBundle\Application\Catalog\GetProductCatalog\GetProductCatalogQuery

    App\WebshopBundle\Application\Cart\CreateCart\CreateCartHandler:
        tags:
            -   name: messenger.message_handler
                handles: App\WebshopBundle\Application\Cart\CreateCart\CreateCartCommand

    App\WebshopBundle\Application\Cart\AddToCart\AddToCartHandler:
        tags:
            -   name: messenger.message_handler
                handles: App\WebshopBundle\Application\Cart\AddToCart\AddToCartCommand

    App\WebshopBundle\Application\Cart\GetCart\GetCartHandler:
        tags:
            -   name: messenger.message_handler
                handles: App\WebshopBundle\Application\Cart\GetCart\GetCartQuery

    App\WebshopBundle\Application\Cart\RemoveItemFromCart\RemoveItemFromCartHandler:
        tags:
            -   name: messenger.message_handler
                handles: App\WebshopBundle\Application\Cart\RemoveItemFromCart\RemoveItemFromCartCommand

    App\WebshopBundle\Application\Checkout\CreateCheckout\CreateCheckoutHandler:
        tags:
            - name: messenger.message_handler
              handles: App\WebshopBundle\Application\Checkout\CreateCheckout\CreateCheckoutQuery

    App\WebshopBundle\Application\Checkout\PaymentMethod\CreatePaymentMethodHandler:
        tags:
            - name: messenger.message_handler
              handles: App\WebshopBundle\Application\Checkout\PaymentMethod\CreatePaymentMethodQuery


    App\WebshopBundle\Application\Checkout\ShippingMethod\CreateShippingMethodHandler:
        tags:
            - name: messenger.message_handler
              handles: App\WebshopBundle\Application\Checkout\ShippingMethod\CreateShippingMethodQuery

    App\WebshopBundle\Application\Checkout\Customer\CreateCustomerHandler:
        tags:
            - name: messenger.message_handler
              handles: App\WebshopBundle\Application\Checkout\Customer\CreateCustomerCommand


    App\WebshopBundle\Application\Shipping\GetShipping\GetShippingHandler:
        tags:
            - name: messenger.message_handler
              handles: App\WebshopBundle\Application\Shipping\GetShipping\GetShippingQuery

    App\WebshopBundle\Application\Payment\GetPayment\GetPaymentHandler:
        tags:
            - name: messenger.message_handler
              handles: App\WebshopBundle\Application\Payment\GetPayment\GetPaymentQuery

    App\WebshopBundle\Application\Checkout\GetCheckout\GetCheckoutHandler:
        tags:
            - name: messenger.message_handler
              handles: App\WebshopBundle\Application\Checkout\GetCheckout\GetCheckoutHandler

    App\WebshopBundle\Application\Checkout\ConfirmCheckout\ConfirmCheckoutHandler:
        tags:
            -   name: messenger.message_handler
                handles: App\WebshopBundle\Application\Checkout\ConfirmCheckout\ConfirmCheckoutCommand
